[project]
name = "stytch-python-magic-links"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask[async]~=2.2",
    "python-dotenv~=0.20",
    "stytch~=7.6",
    "virtualenv>=20.27.1",
]
